"""
reports.py
----------
Generates professional PDF reports (daily summary, service performance,
prediction accuracy) using ReportLab, and logs each generated report in the
`reports` table so admins can browse report history.
"""

import os
import logging
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)

from config import Config
from database import db, today_str
import analytics

logger = logging.getLogger("queuesense.reports")

styles = getSampleStyleSheet()
TITLE_STYLE = ParagraphStyle(
    "QSTitle", parent=styles["Title"], textColor=colors.HexColor("#4338CA"), fontSize=22
)
HEADING_STYLE = ParagraphStyle(
    "QSHeading", parent=styles["Heading2"], textColor=colors.HexColor("#1E293B"), spaceBefore=14
)
BODY_STYLE = styles["BodyText"]


def _ensure_dir():
    os.makedirs(Config.REPORT_DIR, exist_ok=True)


def _table_from_rows(headers, rows, col_widths=None):
    data = [headers] + rows
    table = Table(data, colWidths=col_widths)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4338CA")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F5F9")]),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return table


def generate_daily_report(queue_date: str = None, generated_by: str = "admin") -> str:
    """Generate a daily operations summary PDF and return its file path."""
    _ensure_dir()
    queue_date = queue_date or today_str()
    filename = f"daily_report_{queue_date}_{datetime.now().strftime('%H%M%S')}.pdf"
    filepath = os.path.join(Config.REPORT_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    elements = []

    elements.append(Paragraph("QueueSense-AI", TITLE_STYLE))
    elements.append(Paragraph(f"Daily Operations Report — {queue_date}", HEADING_STYLE))
    elements.append(Spacer(1, 12))

    summary = analytics.todays_summary()
    summary_rows = [
        ["Total Tokens", str(summary["total_tokens"])],
        ["Completed", str(summary["completed_tokens"])],
        ["Cancelled / Skipped", str(summary["cancelled_tokens"])],
        ["Still Waiting", str(summary["waiting_tokens"])],
        ["Average Wait (min)", str(summary["avg_wait_minutes"])],
    ]
    elements.append(_table_from_rows(["Metric", "Value"], summary_rows, col_widths=[8 * cm, 6 * cm]))
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("Service Breakdown", HEADING_STYLE))
    breakdown = analytics.service_breakdown(queue_date)
    service_rows = [[label, str(val)] for label, val in zip(breakdown["labels"], breakdown["values"])]
    if service_rows:
        elements.append(_table_from_rows(["Service", "Tokens Booked"], service_rows, col_widths=[10 * cm, 4 * cm]))
    else:
        elements.append(Paragraph("No tokens booked for this date.", BODY_STYLE))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Average Waiting Time by Service", HEADING_STYLE))
    wait_by_service = analytics.average_waiting_time_by_service()
    wait_rows = [[label, f"{val} min"] for label, val in zip(wait_by_service["labels"], wait_by_service["values"])]
    if wait_rows:
        elements.append(_table_from_rows(["Service", "Avg Wait"], wait_rows, col_widths=[10 * cm, 4 * cm]))
    else:
        elements.append(Paragraph("No completed tokens with recorded wait times yet.", BODY_STYLE))

    elements.append(Spacer(1, 24))
    elements.append(
        Paragraph(
            f"Generated by {generated_by} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            ParagraphStyle("Footer", parent=BODY_STYLE, textColor=colors.grey, fontSize=8),
        )
    )

    doc.build(elements)

    db.execute(
        """INSERT INTO reports (report_type, file_path, generated_by, date_from, date_to)
           VALUES ('daily', ?, ?, ?, ?)""",
        (filename, generated_by, queue_date, queue_date),
        commit=True,
    )
    logger.info("Generated daily report: %s", filepath)
    return filepath


def generate_accuracy_report(generated_by: str = "admin") -> str:
    """Generate a PDF report focused on AI prediction accuracy over time."""
    _ensure_dir()
    filename = f"accuracy_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(Config.REPORT_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    elements = [
        Paragraph("QueueSense-AI", TITLE_STYLE),
        Paragraph("AI Prediction Accuracy Report", HEADING_STYLE),
        Spacer(1, 12),
    ]

    acc = analytics.prediction_accuracy()
    if acc["overall_accuracy"] is not None:
        elements.append(
            Paragraph(f"Overall model accuracy: <b>{acc['overall_accuracy']}%</b>", BODY_STYLE)
        )
        elements.append(Spacer(1, 12))
        rows = [[label, f"{val}%"] for label, val in zip(acc["labels"], acc["values"])]
        elements.append(_table_from_rows(["Date", "Accuracy"], rows, col_widths=[8 * cm, 6 * cm]))
    else:
        elements.append(Paragraph("Not enough completed tokens yet to measure accuracy.", BODY_STYLE))

    elements.append(Spacer(1, 24))
    elements.append(
        Paragraph(
            f"Generated by {generated_by} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            ParagraphStyle("Footer", parent=BODY_STYLE, textColor=colors.grey, fontSize=8),
        )
    )

    doc.build(elements)

    db.execute(
        """INSERT INTO reports (report_type, file_path, generated_by)
           VALUES ('accuracy', ?, ?)""",
        (filename, generated_by),
        commit=True,
    )
    logger.info("Generated accuracy report: %s", filepath)
    return filepath


def list_reports():
    return db.execute("SELECT * FROM reports ORDER BY created_at DESC")
